on:
  push:
    branches:
      - main # This trigger only fires AFTER the Senior SRE merges the code!

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          # ... other security tokens

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: The Auto-Deploy
        run: |
          terraform init
          terraform apply -auto-approve
